### ISSUE TITLE
SS-2016 master issue

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#161]
- bio
  - [x] #153 
  - [x] #159 
  - ~~[ ] #162~~ postponed
    - (?) Poster: http://conferences.au.dk/algo16/wabi/
    - Seminar. Result discussion. (September?)
    - Some additional materials: http://www.sciencedirect.com/science/article/pii/S0167701216300112
- [x] Paper on Graph Parsing: http://www.isgroup.unimore.it/graphq2017/call-for-papers.asp
  - Paper submission: November 14
- F*
  - ~~[ ] #112~~ postponed
  - [x] #160
- Abstract parsing
  - [ ] #117 
- Other
  - [x] [QG](https://github.com/YaccConstructor/QuickGraph/issues/142)
  - [x] [QG](https://github.com/YaccConstructor/QuickGraph/issues/3)
