### ISSUE TITLE
Graph parsing demo

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#174]
Create demo web application for graph parsing.
Technology: [WebSharper](http://websharper.com/)
Small demo: https://github.com/YaccConstructor/YC.Bio.Web ; http://bio-3.apphb.com/

One of possible ways to graph visualization -- Raphael plugin:
- https://bitbucket.org/IntelliFactory/force-graph/
- http://websharper.com/samples/Raphael#void
# Tasks:
- [ ] Create project infrastructure by using ProjectScaffold
  - [ ] Create project page
- [ ] Transfer project to YaccConstructor organization
- [ ] Use https://appharbor.com/ for application hosting
- [ ] Fix user requirements and technical requirements
- [ ] Create technical documentation
- [ ] Technical tasks assignment
- [ ] Create app
  - [ ] Web UI
  - [ ] #173 
  - [ ] #172 
  - [ ] #170

**Comment by KochetovKirill** [comment]
Кочетов, Шаламов и может быть кто-то ещё

**Comment by KrylovBoris** [comment]
Крылов — это кто-то ещё, но, возможно будет ещё кто-то.
