### ISSUE TITLE
Bio graph parsing web demo

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#175]
Create demo web application for bio graph parsing (RNA search).
Technology: [WebSharper](websharper.com)
Small demo: https://github.com/YaccConstructor/YC.Bio.Web ; http://bio-3.apphb.com/

One of possible ways to graph visualization -- Raphael plugin:
- https://bitbucket.org/IntelliFactory/force-graph/
- http://websharper.com/samples/Raphael#void
- http://dmitrybaranovskiy.github.io/raphael/graffle.html
- http://dmitrybaranovskiy.github.io/raphael/
# Tasks:
- [ ] Create project infrastructure by using ProjectScaffold
  - [ ] Create project page
- [ ] Transfer project to YaccConstructor organization
- [ ] Use https://appharbor.com/ for application hosting
- [ ] Fix user requirements and technical requirements
- [ ] Create technical documentation
- [ ] Technical tasks assignment
- [ ] Create app
  - [ ] Web UI
  - [ ] **\*

**Comment by LuninaPolina** [comment]
Маллабаев, Сусанина, Лунина
