### ISSUE TITLE
Software engineering task

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#199]
It is "classical" software engineering task. Result of your work should be a great product for parsing-related solutions creation. 
- [ ] Architecture refactoring. Propose and implment.
     - [ ] You should propose great architecture for this problem solution: #183 
     - [ ] Small additinal refactoring required: #169
- [ ] Examples, documentation, etc 
     - [ ] Existing examples improvements: #198
     - [ ] Autogenerated documentation
     - [ ] More examples: GLL, Graph parsing 
- [ ] Build process automation
  - [ ] Build for Mono: #195 
  - [ ] Code style checking: #78
